# Generated by Django 3.0.5 on 2021-05-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20210510_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(null=True, upload_to='img/%y'),
        ),
        migrations.AlterField(
            model_name='book',
            name='Price',
            field=models.IntegerField(default='330', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='Qty',
            field=models.IntegerField(default='20'),
        ),
    ]
